#include "algiebra.h"

int main() {
	int x;
	int y;
	int** a;
	int** b;
	int** c;
	int** d;
	printString("Calculating gcd(123,456)... ");
	printNewLine();
	x = gcd(123,456);
	printString("Calculating gcdExt(123,456)... ");
	printNewLine();
	y = gcdExt(123,456);
	printString("Calculating getAddModTable(5)... ");
	printNewLine();
	a = getAddModTable(5);
	printString("Calculating getSubModTable(5)... ");
	printNewLine();
	b = getSubModTable(5);
	printString("Calculating getMulModTable(5)... ");
	printNewLine();
	c = getMulModTable(5);
	printString("Calculating getDivModTable(5)... ");
	printNewLine();
	d = getDivModTable(5);
	printNewLine();
	printString("sizeof(x) = ");
        printInteger(sizeof(x));
	printNewLine();
	printString("sizeof(y) = ");
        printInteger(sizeof(y)); 
	printNewLine();
	printString("sizeof(a) = ");
	printInteger(sizeof(a));
	printNewLine();
	printString("sizeof(b) = ");
	printInteger(sizeof(b));
        printNewLine();
	printString("sizeof(c) = ");
        printInteger(sizeof(c));
	printNewLine();
	printString("sizeof(d) = ");
        printInteger(sizeof(d));
	printNewLine();
	printNewLine();
	printInteger(x);
	printNewLine();
	printNewLine();
	printInteger(y);
	printNewLine();
	printNewLine();
	printTable(a, 5);
	printNewLine();
	printTable(b, 5);
	printNewLine();
	printTable(c, 5);
	printNewLine();
	printTable(d, 5);
	printNewLine();
	removeTable(a, 5);
	removeTable(b, 5);
	removeTable(c, 5);
	removeTable(d, 5);
	return 0;
}
